title: "Cam Soper"
description: >
  Developer Educator • Community Builder • Technical Storyteller<br/> 
  Email/Microsoft Teams: cam.soper@outlook.com<br/>
  LinkedIn: [linkedin.com/in/camthegeek](https://www.linkedin.com/in/camthegeek)<br/>  
  GitHub: [github.com/camsoper](https://github.com/camsoper)
theme: jekyll-theme-slate
