title: "Cam Soper"
description: >
  Developer Educator • Community Builder • Technical Storyteller  
  Email/Microsoft Teams: cam.soper@outlook.com  
  LinkedIn: linkedin.com/in/camthegeek  
  GitHub: github.com/camsoper
theme: jekyll-theme-slate
