name: Generate and Commit Resume PDF

on:
  push:
    paths:
      - 'resume.md'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc, LaTeX, and Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex fonts-liberation

      - name: Convert Markdown to PDF
        run: |
          mkdir -p docs
          pandoc resume.md -o docs/cam_soper_resume.pdf --pdf-engine=xelatex

      - name: Commit and Push PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/cam_soper_resume.pdf.pdf
          git commit -m "Automated PDF update from resume.md"
          git push
